### ISSUE TITLE
Stopped status is not printed until player is resumed (playerctl --follow metadata)

### ISSUE THREAD

**Issue by xPMo** [altdesktop/playerctl#115]
**To reproduce:**

```
$ playerctl --follow metadata '{{status}} {{duration(position)}}'
```
Now play your player. Output will be:
```
Playing 0:00
Playing 0:01
Playing 0:02
...
```
Pause the player, and immediately it will change to `Paused X:XX`, as expected.
However, if the player is stopped, playerctl will output a blank line.
Then, when the player is resumed, playerctl will immediately output:
```
Stopped 0:00
Playing 0:00
```
...and then continue as normal.

**Expected  behaviour:**

When the player is stopped, playerctl should immediately output `Stopped 0:00`.

**Comment by acrisci** [comment]
Playerctl is printing the blank line because the metadata has cleared. This is unfortunately going to be player dependent because they follow the spec in different ways. VLC is not clearing the metadata on stop. What player are you using?

The tricky case that needs to be considered is when metadata is involved in the format string. For instance:

```
$ playerctl --follow metadata '{{status}} {{duration(position)}} {{artist}}'
```
What does `{{artist}}` expand to in that case? If it expands to a default, you lose the main use case of being notified when the metadata clears by the blank line which is a problem. So how do you deal with that case?

If instead you don't want metadata, try

```
$ playerctl --follow status '{{status}} {{duration(position)}}'
```

Which should more easily accommodate what you're trying to do because status shouldn't be invalidated while the player is running, so you don't have the problem of needing to be notified of the property invalidation with the new line.

**Comment by xPMo** [comment]
> What player are you using?

I am using Clementine. The example I gave was what I thought was smallest reproducible case, but my real issue is when I want both metadata and status (for [my i3blocks blocklet](https://github.com/xPMo/i3wm-config/blob/gaps/LIB/i3blocks/playerctl.sh#L10)).
I was unaware that a blank line is representative of "metadata is cleared", if this is standard behavior, I will try and implement that in my script's logic.

I want to follow both at once in my script, so my *wish* would be to `--follow all` or allow multiple `--follow`, either of which will fail without a format spec.

**Comment by acrisci** [comment]
I think what you want is supported now by giving all the players you want to follow to the `--player` flag in a comma separated list.
