### ISSUE TITLE
Missing installers from Releases

### ISSUE THREAD

**Issue by fcastilloec** [altdesktop/playerctl#166]
The latest releasee, v2.1.1, is missing `.deb` and `.rpm` installers. I was trying to find any documentation if this installers are not going to be provided anymore, or if they've been moved somewhere else.
It'll be great if you can keep providing these installers, they make use of your software so much easier. Or at least, mention on the release tag as a change that they won't be provided anymore (I hope not :crossed_fingers:)

**Comment by acrisci** [comment]
I've provided them on the release page, but I don't want to do that forever since now both debian and fedora make official packages and I'd rather people use those. You can download them from the official website.

If you want to make packages yourself, check out the `fpm-packages.sh` script and the installing instructions. I'll leave those around indefinitely.

**Comment by fcastilloec** [comment]
Thanks for the info, maybe update the README so everybody knows about this and how to create them.
