### ISSUE TITLE
Feature Request: Implement Quit() method from org.mpris.MediaPlayer2

### ISSUE THREAD

**Issue by alexdelorenzo** [altdesktop/playerctl#171]
The player I am using is [chromecast_mpris](https://github.com/alexdelorenzo/chromecast_mpris) and Plasma Desktop browser integration.

In the MPRIS spec, `org.mpris.MediaPlayer2` provides a `Quit()` method that will quit the media player application. 

If you're open to new features, I wouldn't mind implementing it. 

There's also `Raise()` and `Fullscreen()` from the same section of the spec.

**Comment by acrisci** [comment]
What's the use case for these? The most common use of Playerctl is binding actions to media keys. The window manager has its own bindings for these window actions. `Quit` can be accomplished with your alt-f4 equivalent.

**Comment by acrisci** [comment]
If anyone sees a use case for this you can reopen.

**Comment by pabs3** [comment]
@acrisci Please reopen this issue if you find the following use-cases compelling:

The MPRIS D-Bus documentation says that the Quit command should be implemented for media players with no user interface (for example a command-line, D-Bus activated or daemon based player). I think that is a valid use-case for this option. Since chromecast_mpris mentioned by @alexdelorenzo is now a daemon called [cast_control](https://github.com/alexdelorenzo/cast_control), I think their use-case fits.

https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Method:Quit
https://pythonhosted.org/mpris2/mpris2.mediaplayer2.html#mpris2.mediaplayer2.MediaPlayer2.Quit

In addition, [mpv-mpris](https://github.com/hoyon/mpv-mpris) supports the MPRIS Quit API and I would like to add support to the mpv-mpris test suite to make sure that this Quit support works. I would prefer to use playerctl for sending the Quit command if possible. Since playerctl is a useful tool for testing applications that support MPRIS, I think it should support all of the MPRIS D-Bus API, including the Quit API.

I would like to send a pull request for adding this feature if you will accept that Quit has valid use-cases.
