### ISSUE TITLE
Feature request: fail loudly when a player doesn't support a command.

### ISSUE THREAD

**Issue by sagotsky** [altdesktop/playerctl#232]
I'm using playerctl to control spotify.  I wanted to use `playerctl volume`.  The cli gave the appearance of having worked, but there was no change in volume.

I found https://github.com/altdesktop/playerctl/issues/156 pretty quickly.  That's fine, I don't expect y'all to fix spotify's implementation.

What would be awesome though is if playerctl could tell me that instead of appearing to work and letting me google why it didn't.  `warning: spotify doesn't support volume` in STDOUT would be much appreciated.  I don't know if mpris exposes what capabilities each client has or if clients would be truthful about what capabilities work, but if they do that would be a pretty low lift relatively speaking.

**Comment by acrisci** [comment]
Spotify is telling me it changed the volume successfully. If they gave me an error on the call, I would report it but they don't.

I'd prefer not to put this in the code because I don't think it's worth it to maintain. The feature doesn't scale because to do it properly, every player would require 3-4 warnings and I'm going to have hundreds of warnings in my code that requires a version bump whenever they change.

If you'd like to maintain player support status in a separate document in the repo, I would appreciate that work.

Here's a letter template you can send to spotify with your complaints.

https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md

**Comment by sagotsky** [comment]
That sucks.  I didn't expect them to lie about whether the command worked.  Totally agree it's not playerctl's job to maintain a list of known lies different apps will tell you.

**Comment by acrisci** [comment]
If you want to do a fun project, you could make an "mpris tester" app that tests all the features a player supports and generates a report automatically with a detailed compatibility score. Then anyone could run this on a player and submit reports into the document.
