### ISSUE TITLE
Suggestion: `playerctl --list-all` should output nothing if there are no players running

### ISSUE THREAD

**Issue by jmcantrell** [altdesktop/playerctl#257]
If there are no players running, then the output is "No players found". When using this output in a script, there's no good way to tell if there are no players running, except to compare the output to that string. In my opinion, this is very brittle, and the standard/expected result when running a list command is that if there is nothing to list, then there should be no output.

**Comment by acrisci** [comment]
That's printed to stdout. Just filter that out and you will get what you want.

**Comment by jmcantrell** [comment]
Right, stdout would be the correct place to output it. I still think it's non-standard to output something when there's nothing to output. What purpose does it serve?

**Comment by acrisci** [comment]
It's standard to output useful diagnostic messages in stderr. It's useful in this case because it's probably the number one reported message on this issue tracker, and it's easier to report and understand than "exit 0 with no output" which may be confused with some other problem if you aren't familiar with the project.

**Comment by jmcantrell** [comment]
Thanks for the explanation.
